### ISSUE TITLE
关于代码视图的建议

### ISSUE THREAD

**Issue by Fxiao1** [vnotex/vnote#1079]
OS Version (操作系统): Windows, Linux, macOS
win10
VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..
2.7.2
Symptoms (表现):
目前代码的视图模式有一个缺陷，比如，当代码过宽且过长的时候，有一部分的代码会跑到右边，但是横向滑动条却不在当前可视范围内，需要先滑到底部，找到横向滑动条，向右滑动，但在此时，又看不到上面的代码了。如下图所示
![Snipaste_2019-11-21_11-32-11](https://user-images.githubusercontent.com/40653617/69301924-cf1f2d80-0c52-11ea-83df-23f61500f78b.png)
所以我建议，将代码框设置为一个固定大小的框宽1000px，高950px，拥有独立的横向和竖向滑动条。就像一般的编辑器，如下图
![Snipaste_2019-11-21_11-39-34](https://user-images.githubusercontent.com/40653617/69302158-aba8b280-0c53-11ea-8d21-b97032e761dd.png)

How to Repro (如何复现):

**Comment by yousifun** [comment]
这个好像通过主题的css可以实现，你自己在浏览器可以调试一下。我的方法是直接换行。

**Comment by Fxiao1** [comment]
找到解决办法了，确实是通过css实现，文件为
"C:\Users\自己电脑的用户名\AppData\Roaming\vnote\themes\v_pure_myself\当前应用的主题名.css"
找“pre code”
添加如下两行，分别设置超出出现滑动条，和最大高度为650px
```css
overflow-y: auto;
max-height: 650px;
```
修改后的代码为
```css
pre code {
    display: block;
    overflow-x: auto;
    overflow-y: auto;
    max-height: 650px;
    padding: 0.5em;
    color: #222222;
    background-color: #E0E0E0;
    border-left: .5em solid #00897B;
    line-height: 1.5;
    font-family: Consolas, Monaco, Monospace, Courier;
    white-space: pre;
    -moz-tab-size: 4;
    -o-tab-size: 4;
    tab-size: 4;
}
```
