### ISSUE TITLE
VNote界面自定义字体大小

### ISSUE THREAD

**Issue by tamlok** [vnotex/vnote#1214]
如果VNote默认的字体大小效果不好，例如某些界面的字体可能特别小，可以通过修改所用主题的`*.qss`文件来实现自定义字体大小。

以下所有内容请添加到`*.qss`文件的顶部。

## 文件夹树
![image](https://user-images.githubusercontent.com/5763157/74731942-1930a300-5284-11ea-853e-f87dc6806216.png)

```css
VDirectoryTree {
    font-size: 15pt;
}
```

## 笔记列表
![image](https://user-images.githubusercontent.com/5763157/74731993-36fe0800-5284-11ea-856b-95383726eba0.png)

```css
VFileList QListView {
    font-size: 15pt;
}
```

## 菜单
![image](https://user-images.githubusercontent.com/5763157/74732106-7298d200-5284-11ea-912e-9e2a24897857.png)

```css
QMenuBar {
    font-size: 15pt;
}
```

## 大纲
![image](https://user-images.githubusercontent.com/5763157/74732555-737e3380-5285-11ea-98d8-46ef54ff5752.png)

```css
VOutline QTreeWidget {
    font-size: 15pt;
}
```

**Comment by philipatc** [comment]
你好，我嘗試過，但我在 Linux 因為沒有以上字體， 所有的中文到變了亂碼（Tab, ListView, TreeView)
我試了改 QWidget font-family : "Noto Sans Mono CJK TC", 但在 Preview Mode 沒事， Edit Mode 也是亂碼

**Comment by tamlok** [comment]
编辑模式是mdhl文件定义的，具体参考官方文档。缺失字体问题建议安装对应字体。

**Comment by rfcpdq** [comment]
I use Linux, my solution is changing vnote.desktop (120% scaling for example):
Exec=/usr/bin/env QT_AUTO_SCREEN_SCALE_FACTOR=0 QT_SCALE_FACTOR=1.2 VNote %F

**Comment by unihon** [comment]
可在主题配置文件`*.qss`中加入如下样式设置全局的默认字体大小。
``` css
*{
   font-size: 12pt;
}
```
