### ISSUE TITLE
请求为单行代码添加独立的class

### ISSUE THREAD

**Issue by Fxiao1** [vnotex/vnote#1906]
# vnote版本 3.8.1
# 问题描述

现在我遇到了一个问题，想给单行代码和多行代码添加对应的效果，但是现在我发现多行代码的`<code>`标签有对应的class修饰（`.source-line`），但单行代码却没有任何class修饰，所以我难以对他俩分别做出区别修饰。因为如果修饰单行，就得对`<code>`标签直接修饰，但然而修饰的效果却会污染到多行代码的效果。求大佬能对单行代码添加一个特有的class，方便用户自定义主题

```css
code {
    font-family: "YaHei Consolas Hybrid", Consolas, Monaco, Monospace, Courier;
    color: #8e24aa;
    word-break: break-word;
}
```
```css
pre code {
    display: block;
    padding-left: 0.5em;
    padding-right: 0.5em;
    color: #222222;
    background-color: #e0e0e0;
    line-height: 1.5;
    font-family: "YaHei Consolas Hybrid", Consolas, Monaco, Monospace, Courier;
    white-space: pre;
    -moz-tab-size: 4;
    -o-tab-size: 4;
    tab-size: 4;
}
```

**Comment by Fxiao1** [comment]
后面的时候我发现单行代码的`<code>`都在`li.source-line`里面，所以如果我们只需要修改单行代码定义的话，只需要缩小选择的范围即可

1. 打开当前主题文件夹中的web.css
2. 在`code`定义下面新增`.source-line code`的定义：如下

```css
code {
    font-family: "YaHei Consolas Hybrid", Consolas, Monaco, "Andale Mono", Monospace, "Courier New";
    color: #8e24aa;
    word-break: break-word;
}

.source-line code {
    /*1.水平阴影  2.垂直阴影 3.模糊距离，改虚实 4.阴影尺寸,5.阴影颜色*/
    box-shadow: 2px 2px 2px 1px rgba(0,0,0,0.2);
    background-color:#e9e9e9;
    /*左右边距增加3px*/
    margin:0px 3px;
}
```
