### ISSUE TITLE
The LaTeX math expressions cannot be scaled when I scaled the fonts.

### ISSUE THREAD

**Issue by PamlJam** [vnotex/vnote#2364]
**Screenshots**
![image](https://user-images.githubusercontent.com/61358458/226105468-45525c0b-348d-4027-9100-b277ba51358b.png)

**Comment by halvabner** [comment]
same for me, unusable. have you found a solution?

**Comment by halvabner** [comment]
i think there could be a chance of this getting fixed by adding something like
```css
.MathJax {
  font-size: 1.3em;
}
```
in perhaps `web.css` in or another file in your current theme

but the problem i noticed is that there is a chance that by using the built in zooming functionality it might not be changing css at all, something else.

maybe a developer of the project can help us?

**Comment by halvabner** [comment]
i tried editing web.css to have
```css
p, ul, ol, eqn {
    font-size: 16px;
    line-height: 24px;
}
```
(i added `eqn`) but still the zoom functionality doesn't affect eqn blocks. perhaps @tamlok can give us a hint?
