### ISSUE TITLE
预览显示与pdf导出的显示不一致

### ISSUE THREAD

**Issue by LostEcho-TeaParty** [vnotex/vnote#2490]
**Describe the bug**
我很喜欢使用vnote，但这个问题困扰了我很久，我只单纯的安装了vnote，没有安装web.css里面说明的非默认字体。

在预览显示如下：
![image](https://github.com/vnotex/vnote/assets/47772285/d27f9237-143f-4e6c-a2b6-8091978fd1d2)

但是使用wkhtmltopdf导出的pdf显示如下
![image](https://github.com/vnotex/vnote/assets/47772285/605cf789-2d09-47e6-a0e8-62edd1ba9b64)

可以发现，导出的pdf的字体与预览的不同，pdf的排版、字体都非常好看，我能不能让预览显示和pdf导出一样好看呢。
我找到了theme的web.css，里面`body`中描述的`font-family`很多我都没有安装，可为什么导出的pdf会有些非默认字体呢？
```css
body {
    font-family: "YaHei Consolas Hybrid", "Noto Sans", "Helvetica Neue", "Segoe UI", Helvetica, Tahoma, Arial, Geneva, Georgia, Palatino, "Times New Roman", "冬青黑体", "Microsoft YaHei", "微软雅黑", "Microsoft YaHei UI", "WenQuanYi Micro Hei", "文泉驿雅黑", Dengxian, "等线体", STXihei, "华文细黑", "Liberation Sans", "Droid Sans", NSimSun, "新宋体", SimSun, "宋体", "Apple Color Emoji", "Segoe UI Emoji";
}
```

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11]
 - Version [e.g. 3.17.0]
